# Generated by Django 4.0 on 2021-12-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('proj_type', models.CharField(choices=[('BACK_END', 'back_end'), ('FRONT_END', 'front_end'), ('IOS', 'ios'), ('ANDROID', 'android')], max_length=16, verbose_name='project_type')),
            ],
        ),
    ]
