# Generated by Django 4.0 on 2021-12-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk_API', '0003_alter_issue_assignee_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
