# Generated by Django 4.0 on 2021-12-12 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SoftDesk_API', '0007_alter_project_author_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee_user_id',
            field=models.ManyToManyField(default=models.ManyToManyField(related_name='author', to=settings.AUTH_USER_MODEL), related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'high'), ('MEDIUM', 'medium'), ('LOW', 'low')], max_length=16),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'to_do'), ('ONGOING', 'ongoing'), ('FINISH', 'finish')], max_length=16),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'bug'), ('IMPROVEMENT', 'improvement'), ('TASK', 'task')], max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_type',
            field=models.CharField(choices=[('BACK_END', 'back_end'), ('FRONT_END', 'front_end'), ('IOS', 'ios'), ('ANDROID', 'android')], max_length=16, verbose_name='project_type'),
        ),
    ]
