# Generated by Django 4.0 on 2021-12-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk_API', '0009_alter_contributor_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author_user_id',
        ),
    ]
