# Generated by Django 4.0 on 2021-12-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0002_remove_contributor_user_id_contributor_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'author'), ('CONTRIBUTOR', 'contributor')], default='CONTRIBUTOR', max_length=16),
        ),
    ]
