# Generated by Django 4.0 on 2021-12-13 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=1024)),
                ('tag', models.CharField(choices=[('BUG', 'bug'), ('IMPROVEMENT', 'improvement'), ('TASK', 'task')], max_length=16)),
                ('priority', models.CharField(choices=[('HIGH', 'high'), ('MEDIUM', 'medium'), ('LOW', 'low')], max_length=16)),
                ('status', models.CharField(choices=[('TO_DO', 'to_do'), ('ONGOING', 'ongoing'), ('FINISH', 'finish')], max_length=16)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assignee_user_id', models.ManyToManyField(default=models.ManyToManyField(related_name='author', to=settings.AUTH_USER_MODEL), related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('author_user_id', models.ManyToManyField(related_name='author', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
